/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.sotino.view;

import be.sotino.entity.combatant.Archer;
import be.sotino.entity.combatant.Combatant;
import be.sotino.entity.combatant.Phalange;
import be.sotino.entity.combatant.RangingUnit;
import be.sotino.entity.construction.Centurion;

/**
 *
 * @author Simon
 */
public class CombatantDetail extends javax.swing.JPanel {
    
    private Combatant combatant;
    private Centurion centurion;

    /**
     * Creates new form CombatantDetail
     */
    public CombatantDetail() {
        initComponents();
    }

    public CombatantDetail(Centurion centurion,Combatant c) {
        initComponents();
        this.centurion = centurion;
        combatant = c;
        if(!(c instanceof RangingUnit)){
            rangeTF.setVisible(false);
            rangeLabel.setVisible(false);
        }else{
            rangeTF.setText(""+((RangingUnit)combatant).getRange());
        }
        ressource1.setPlayerRessource(combatant.getPrice());
        vieTF.setText(""+combatant.getLife());
        attaqueTF.setText(""+combatant.getDegat());
        defenseTF.setText(""+combatant.getDefence());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ressource1 = new be.sotino.view.Ressource();
        buyBouton = new javax.swing.JButton();
        vieLabel = new javax.swing.JLabel();
        vieTF = new javax.swing.JTextField();
        attaqueTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        defenseTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rangeTF = new javax.swing.JTextField();
        rangeLabel = new javax.swing.JLabel();

        buyBouton.setText("Buy");
        buyBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBoutonActionPerformed(evt);
            }
        });

        vieLabel.setText("vie :");

        vieTF.setText("999");

        attaqueTF.setText("999");

        jLabel2.setText("Attaque:");

        defenseTF.setText("999");

        jLabel3.setText("Defense:");

        rangeTF.setText("999");

        rangeLabel.setText("range:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ressource1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(buyBouton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vieLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vieTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(attaqueTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(defenseTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rangeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rangeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vieLabel)
                    .addComponent(vieTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(attaqueTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(defenseTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rangeLabel)
                    .addComponent(rangeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ressource1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(buyBouton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buyBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBoutonActionPerformed
        if(combatant instanceof Phalange){
            centurion.buyPhalange();
        }else if(combatant instanceof Archer){
            centurion.buyArcher();
        }
    }//GEN-LAST:event_buyBoutonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attaqueTF;
    private javax.swing.JButton buyBouton;
    private javax.swing.JTextField defenseTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel rangeLabel;
    private javax.swing.JTextField rangeTF;
    private be.sotino.view.Ressource ressource1;
    private javax.swing.JLabel vieLabel;
    private javax.swing.JTextField vieTF;
    // End of variables declaration//GEN-END:variables
}
