/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.sotino.view;

import be.sotino.busness.moteur;
import be.sotino.entity.Exploitant;
import be.sotino.entity.Player;
import javax.swing.JFrame;

/**
 *
 * @author Simon
 */
public class PlayerView extends javax.swing.JFrame {
    private Player player;
    private JFrame frame;
    private CommandementCenter commandementCenter;
    private long lastRefresh;

    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
        setTitle("Alera");
        setVisible(true);
        lastRefresh = System.currentTimeMillis();
    }

    public PlayerView(Player player) {
        this();
        this.player=player;
        ressource1.setPlayerRessource(this.player.getRessource());
        selectItem2.setExploitants(this.player.getExploitants());
        notifyChange();
    }
    
    public void notifyChange(){
        long now = System.currentTimeMillis();
        long delta = now -lastRefresh;
        lastRefresh= now;
        for(Exploitant e: player.getExploitants()){
            e.refreshFromDelta(delta);
        }
        ressource1.notifieChange();
        selectItem2.notifieChange();
        if (frame!= null && frame.isVisible()){
            commandementCenter.notifieChange();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ressource1 = new be.sotino.view.Ressource();
        selectItem2 = new be.sotino.view.SelectItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Achat");

        jMenuItem1.setText("Centre de commandement");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(ressource1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(selectItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ressource1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frame = new JFrame("Visulalisation du centre de commandement");
        commandementCenter = new CommandementCenter();
        commandementCenter.setPlayer(player);
        frame.add(commandementCenter);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        Player me = new Player();
//        PlayerView fr = new PlayerView(me);
//        moteur m = new moteur(fr);
//        
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private be.sotino.view.Ressource ressource1;
    private be.sotino.view.SelectItem selectItem2;
    // End of variables declaration//GEN-END:variables
}
