/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.sotino.view;

/**
 *
 * @author Simon
 */
public class Ressource extends javax.swing.JPanel {

    private be.sotino.entity.Ressource playerRessource;
    /**
     * Creates new form Ressource
     */
    public Ressource() {
        initComponents();
    }
    
    public Ressource(be.sotino.entity.Ressource playerRessource){
        this();
        setPlayerRessource(playerRessource);
    }

    public void setPlayerRessource(be.sotino.entity.Ressource playerRessource) {
        this.playerRessource = playerRessource;
        notifieChange();
    }
    
    
    public void notifieChange() {
        woodTF.setText(""+(int)playerRessource.getWood());
        meetTF.setText(""+(int)playerRessource.getMeet());
        goldTF.setText(""+(int)playerRessource.getGold());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        woodTF = new javax.swing.JTextField();
        meetTF = new javax.swing.JTextField();
        goldTF = new javax.swing.JTextField();

        jLabel1.setText("Wood");

        jLabel2.setText("Meet");

        jLabel3.setText("Gold");

        woodTF.setEditable(false);
        woodTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        woodTF.setText("9999");

        meetTF.setEditable(false);
        meetTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        meetTF.setText("9999");

        goldTF.setEditable(false);
        goldTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        goldTF.setText("9999");
        goldTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goldTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(woodTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meetTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(goldTF, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(woodTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meetTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goldTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goldTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goldTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goldTFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField goldTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField meetTF;
    private javax.swing.JTextField woodTF;
    // End of variables declaration//GEN-END:variables

}
