/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.sotino.view;

import be.sotino.entity.Exploitant;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JSlider;

/**
 *
 * @author Simon
 */
public class SelectItem extends javax.swing.JPanel {

    private List<Exploitant> exploitants;
    private JFrame frame;
    private Exploitation exp;

    /**
     * Creates new form SelectItem
     */
    public SelectItem() {
        initComponents();
    }

    public void setExploitants(List<Exploitant> exploitants) {
        this.exploitants = exploitants;
        notifieChange();
    }

    public void notifieChange() {
        int size = exploitants.size();
        if (size != exploitantSlider.getMaximum()) {
            exploitantSlider.setValue(1);
            exploitantSlider.setMinimum(1);
            if (size == 0) {
                exploitantSlider.setValue(0);
                exploitantSlider.setMinimum(0);
            }
            exploitantSlider.setMaximum(size);
        }
        exploitantVutton.setEnabled(size != 0);
        if (frame != null && frame.isVisible()) {
            exp.notifieChange();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        exploitantSlider = new javax.swing.JSlider();
        exploitantVutton = new javax.swing.JButton();

        jLabel1.setText("Exploitant");

        exploitantSlider.setMajorTickSpacing(1);
        exploitantSlider.setMaximum(5);
        exploitantSlider.setMinimum(1);
        exploitantSlider.setPaintLabels(true);
        exploitantSlider.setToolTipText("");
        exploitantSlider.setValue(2);

        exploitantVutton.setText("View");
        exploitantVutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exploitantVuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exploitantSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exploitantVutton)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exploitantVutton)
                    .addComponent(exploitantSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exploitantVuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exploitantVuttonActionPerformed
        frame =new JFrame("Visulalisation de l'exploitation");
        exp = new Exploitation();
        exp.setExploitant(exploitants.get(exploitantSlider.getValue() - 1));
        frame.add(exp);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_exploitantVuttonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider exploitantSlider;
    private javax.swing.JButton exploitantVutton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
